# Generated by Django 5.0.3 on 2024-04-08 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(unique=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('flags', models.ManyToManyField(blank=True, to='question_app.flag')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(unique=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('pointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='question_app.knowledgebase')),
            ],
        ),
    ]
