version: '3.8'

services:
  web:
    build: .
    # command: gunicorn webapp.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/webapp/
      - /usr/src/webapp/__pycache__
    ports:
      - 8000:8000
    env_file:
      - .env

  bot:
    build: .
    command: python manage.py run_telegram_bot
    volumes:
      - .:/usr/src/webapp/
    env_file:
      - .env
    depends_on:
      - web
