version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  web:
    build: .
    # command: gunicorn webapp.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/webapp/
      - /usr/src/webapp/__pycache__
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  bot:
    build: .
    command: python manage.py run_telegram_bot
    volumes:
      - .:/usr/src/webapp/
    env_file:
      - .env
    depends_on:
      - web
      - db

volumes:
  postgres_data: