# Generated by Django 5.0.3 on 2024-03-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_status_service_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_vpn_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
