# Generated by Django 5.0.3 on 2024-03-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_alter_report_is_vpn_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
